/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModeratorsRouteImport } from './routes/moderators'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SocialsRouteImport } from './routes/socials'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesArticleIdRouteImport } from './routes/articles.$articleId'
import { Route as ForumIndexRouteImport } from './routes/forum.index'
import { Route as ForumPostIdRouteImport } from './routes/forum.$postId'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as ApiPublicArticlesRouteImport } from './routes/api/public/articles'
import { Route as ApiPublicAvatarsFileRouteImport } from './routes/api/public/avatars.$file'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeratorsRoute = ModeratorsRouteImport.update({
  id: '/moderators',
  path: '/moderators',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialsRoute = SocialsRouteImport.update({
  id: '/socials',
  path: '/socials',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesArticleIdRoute = ArticlesArticleIdRouteImport.update({
  id: '/articles/$articleId',
  path: '/articles/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumPostIdRoute = ForumPostIdRouteImport.update({
  id: '/forum/$postId',
  path: '/forum/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicArticlesRoute = ApiPublicArticlesRouteImport.update({
  id: '/api/public/articles',
  path: '/api/public/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAvatarsFileRoute = ApiPublicAvatarsFileRouteImport.update({
  id: '/api/public/avatars/$file',
  path: '/api/public/avatars/$file',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/moderators': typeof ModeratorsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/socials': typeof SocialsRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/forum/$postId': typeof ForumPostIdRoute
  '/u/$handle': typeof UHandleRoute
  '/articles/': typeof ArticlesIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/api/public/articles': typeof ApiPublicArticlesRoute
  '/api/public/avatars/$file': typeof ApiPublicAvatarsFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/moderators': typeof ModeratorsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/socials': typeof SocialsRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/forum/$postId': typeof ForumPostIdRoute
  '/u/$handle': typeof UHandleRoute
  '/articles': typeof ArticlesIndexRoute
  '/forum': typeof ForumIndexRoute
  '/api/public/articles': typeof ApiPublicArticlesRoute
  '/api/public/avatars/$file': typeof ApiPublicAvatarsFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/moderators': typeof ModeratorsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/socials': typeof SocialsRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/forum/$postId': typeof ForumPostIdRoute
  '/u/$handle': typeof UHandleRoute
  '/articles/': typeof ArticlesIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/api/public/articles': typeof ApiPublicArticlesRoute
  '/api/public/avatars/$file': typeof ApiPublicAvatarsFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms.txt'
    | '/login'
    | '/moderators'
    | '/sitemap.xml'
    | '/socials'
    | '/articles/$articleId'
    | '/forum/$postId'
    | '/u/$handle'
    | '/articles/'
    | '/forum/'
    | '/api/public/articles'
    | '/api/public/avatars/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms.txt'
    | '/login'
    | '/moderators'
    | '/sitemap.xml'
    | '/socials'
    | '/articles/$articleId'
    | '/forum/$postId'
    | '/u/$handle'
    | '/articles'
    | '/forum'
    | '/api/public/articles'
    | '/api/public/avatars/$file'
  id:
    | '__root__'
    | '/'
    | '/llms.txt'
    | '/login'
    | '/moderators'
    | '/sitemap.xml'
    | '/socials'
    | '/articles/$articleId'
    | '/forum/$postId'
    | '/u/$handle'
    | '/articles/'
    | '/forum/'
    | '/api/public/articles'
    | '/api/public/avatars/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  ModeratorsRoute: typeof ModeratorsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SocialsRoute: typeof SocialsRoute
  ArticlesArticleIdRoute: typeof ArticlesArticleIdRoute
  ForumPostIdRoute: typeof ForumPostIdRoute
  UHandleRoute: typeof UHandleRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  ForumIndexRoute: typeof ForumIndexRoute
  ApiPublicArticlesRoute: typeof ApiPublicArticlesRoute
  ApiPublicAvatarsFileRoute: typeof ApiPublicAvatarsFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderators': {
      id: '/moderators'
      path: '/moderators'
      fullPath: '/moderators'
      preLoaderRoute: typeof ModeratorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/socials': {
      id: '/socials'
      path: '/socials'
      fullPath: '/socials'
      preLoaderRoute: typeof SocialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$articleId': {
      id: '/articles/$articleId'
      path: '/articles/$articleId'
      fullPath: '/articles/$articleId'
      preLoaderRoute: typeof ArticlesArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/': {
      id: '/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$postId': {
      id: '/forum/$postId'
      path: '/forum/$postId'
      fullPath: '/forum/$postId'
      preLoaderRoute: typeof ForumPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/articles': {
      id: '/api/public/articles'
      path: '/api/public/articles'
      fullPath: '/api/public/articles'
      preLoaderRoute: typeof ApiPublicArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/avatars/$file': {
      id: '/api/public/avatars/$file'
      path: '/api/public/avatars/$file'
      fullPath: '/api/public/avatars/$file'
      preLoaderRoute: typeof ApiPublicAvatarsFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  ModeratorsRoute: ModeratorsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SocialsRoute: SocialsRoute,
  ArticlesArticleIdRoute: ArticlesArticleIdRoute,
  ForumPostIdRoute: ForumPostIdRoute,
  UHandleRoute: UHandleRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  ForumIndexRoute: ForumIndexRoute,
  ApiPublicArticlesRoute: ApiPublicArticlesRoute,
  ApiPublicAvatarsFileRoute: ApiPublicAvatarsFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
