/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModeratorsRouteImport } from './routes/moderators'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SocialsRouteImport } from './routes/socials'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesArticleIdRouteImport } from './routes/articles.$articleId'
import { Route as ForumIndexRouteImport } from './routes/forum.index'
import { Route as ForumPostIdRouteImport } from './routes/forum.$postId'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as ApiPublicArticlesRouteImport } from './routes/api/public/articles'
import { Route as ApiPublicCommentsRouteImport } from './routes/api/public/comments'
import { Route as ApiPublicForumRouteImport } from './routes/api/public/forum'
import { Route as ApiPublicAuthLoginRouteImport } from './routes/api/public/auth.login'
import { Route as ApiPublicAuthMeRouteImport } from './routes/api/public/auth.me'
import { Route as ApiPublicAuthRegisterRouteImport } from './routes/api/public/auth.register'
import { Route as ApiPublicAvatarsFileRouteImport } from './routes/api/public/avatars.$file'
import { Route as ApiPublicForumPostIdRouteImport } from './routes/api/public/forum.$postId'
import { Route as ApiPublicForumRulesRouteImport } from './routes/api/public/forum.rules'
import { Route as ApiPublicProfilesHandleRouteImport } from './routes/api/public/profiles.$handle'
import { Route as ApiPublicForumPostIdVoteRouteImport } from './routes/api/public/forum.$postId.vote'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeratorsRoute = ModeratorsRouteImport.update({
  id: '/moderators',
  path: '/moderators',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialsRoute = SocialsRouteImport.update({
  id: '/socials',
  path: '/socials',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesArticleIdRoute = ArticlesArticleIdRouteImport.update({
  id: '/articles/$articleId',
  path: '/articles/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumPostIdRoute = ForumPostIdRouteImport.update({
  id: '/forum/$postId',
  path: '/forum/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicArticlesRoute = ApiPublicArticlesRouteImport.update({
  id: '/api/public/articles',
  path: '/api/public/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCommentsRoute = ApiPublicCommentsRouteImport.update({
  id: '/api/public/comments',
  path: '/api/public/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicForumRoute = ApiPublicForumRouteImport.update({
  id: '/api/public/forum',
  path: '/api/public/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthLoginRoute = ApiPublicAuthLoginRouteImport.update({
  id: '/api/public/auth/login',
  path: '/api/public/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthMeRoute = ApiPublicAuthMeRouteImport.update({
  id: '/api/public/auth/me',
  path: '/api/public/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthRegisterRoute = ApiPublicAuthRegisterRouteImport.update({
  id: '/api/public/auth/register',
  path: '/api/public/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAvatarsFileRoute = ApiPublicAvatarsFileRouteImport.update({
  id: '/api/public/avatars/$file',
  path: '/api/public/avatars/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicForumPostIdRoute = ApiPublicForumPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => ApiPublicForumRoute,
} as any)
const ApiPublicForumRulesRoute = ApiPublicForumRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => ApiPublicForumRoute,
} as any)
const ApiPublicProfilesHandleRoute = ApiPublicProfilesHandleRouteImport.update({
  id: '/api/public/profiles/$handle',
  path: '/api/public/profiles/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicForumPostIdVoteRoute =
  ApiPublicForumPostIdVoteRouteImport.update({
    id: '/vote',
    path: '/vote',
    getParentRoute: () => ApiPublicForumPostIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/moderators': typeof ModeratorsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/socials': typeof SocialsRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/forum/$postId': typeof ForumPostIdRoute
  '/u/$handle': typeof UHandleRoute
  '/articles/': typeof ArticlesIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/api/public/articles': typeof ApiPublicArticlesRoute
  '/api/public/comments': typeof ApiPublicCommentsRoute
  '/api/public/forum': typeof ApiPublicForumRouteWithChildren
  '/api/public/auth/login': typeof ApiPublicAuthLoginRoute
  '/api/public/auth/me': typeof ApiPublicAuthMeRoute
  '/api/public/auth/register': typeof ApiPublicAuthRegisterRoute
  '/api/public/avatars/$file': typeof ApiPublicAvatarsFileRoute
  '/api/public/forum/$postId': typeof ApiPublicForumPostIdRouteWithChildren
  '/api/public/forum/rules': typeof ApiPublicForumRulesRoute
  '/api/public/profiles/$handle': typeof ApiPublicProfilesHandleRoute
  '/api/public/forum/$postId/vote': typeof ApiPublicForumPostIdVoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/moderators': typeof ModeratorsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/socials': typeof SocialsRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/forum/$postId': typeof ForumPostIdRoute
  '/u/$handle': typeof UHandleRoute
  '/articles': typeof ArticlesIndexRoute
  '/forum': typeof ForumIndexRoute
  '/api/public/articles': typeof ApiPublicArticlesRoute
  '/api/public/comments': typeof ApiPublicCommentsRoute
  '/api/public/forum': typeof ApiPublicForumRouteWithChildren
  '/api/public/auth/login': typeof ApiPublicAuthLoginRoute
  '/api/public/auth/me': typeof ApiPublicAuthMeRoute
  '/api/public/auth/register': typeof ApiPublicAuthRegisterRoute
  '/api/public/avatars/$file': typeof ApiPublicAvatarsFileRoute
  '/api/public/forum/$postId': typeof ApiPublicForumPostIdRouteWithChildren
  '/api/public/forum/rules': typeof ApiPublicForumRulesRoute
  '/api/public/profiles/$handle': typeof ApiPublicProfilesHandleRoute
  '/api/public/forum/$postId/vote': typeof ApiPublicForumPostIdVoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/moderators': typeof ModeratorsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/socials': typeof SocialsRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/forum/$postId': typeof ForumPostIdRoute
  '/u/$handle': typeof UHandleRoute
  '/articles/': typeof ArticlesIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/api/public/articles': typeof ApiPublicArticlesRoute
  '/api/public/comments': typeof ApiPublicCommentsRoute
  '/api/public/forum': typeof ApiPublicForumRouteWithChildren
  '/api/public/auth/login': typeof ApiPublicAuthLoginRoute
  '/api/public/auth/me': typeof ApiPublicAuthMeRoute
  '/api/public/auth/register': typeof ApiPublicAuthRegisterRoute
  '/api/public/avatars/$file': typeof ApiPublicAvatarsFileRoute
  '/api/public/forum/$postId': typeof ApiPublicForumPostIdRouteWithChildren
  '/api/public/forum/rules': typeof ApiPublicForumRulesRoute
  '/api/public/profiles/$handle': typeof ApiPublicProfilesHandleRoute
  '/api/public/forum/$postId/vote': typeof ApiPublicForumPostIdVoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms.txt'
    | '/login'
    | '/moderators'
    | '/sitemap.xml'
    | '/socials'
    | '/articles/$articleId'
    | '/forum/$postId'
    | '/u/$handle'
    | '/articles/'
    | '/forum/'
    | '/api/public/articles'
    | '/api/public/comments'
    | '/api/public/forum'
    | '/api/public/auth/login'
    | '/api/public/auth/me'
    | '/api/public/auth/register'
    | '/api/public/avatars/$file'
    | '/api/public/forum/$postId'
    | '/api/public/forum/rules'
    | '/api/public/profiles/$handle'
    | '/api/public/forum/$postId/vote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms.txt'
    | '/login'
    | '/moderators'
    | '/sitemap.xml'
    | '/socials'
    | '/articles/$articleId'
    | '/forum/$postId'
    | '/u/$handle'
    | '/articles'
    | '/forum'
    | '/api/public/articles'
    | '/api/public/comments'
    | '/api/public/forum'
    | '/api/public/auth/login'
    | '/api/public/auth/me'
    | '/api/public/auth/register'
    | '/api/public/avatars/$file'
    | '/api/public/forum/$postId'
    | '/api/public/forum/rules'
    | '/api/public/profiles/$handle'
    | '/api/public/forum/$postId/vote'
  id:
    | '__root__'
    | '/'
    | '/llms.txt'
    | '/login'
    | '/moderators'
    | '/sitemap.xml'
    | '/socials'
    | '/articles/$articleId'
    | '/forum/$postId'
    | '/u/$handle'
    | '/articles/'
    | '/forum/'
    | '/api/public/articles'
    | '/api/public/comments'
    | '/api/public/forum'
    | '/api/public/auth/login'
    | '/api/public/auth/me'
    | '/api/public/auth/register'
    | '/api/public/avatars/$file'
    | '/api/public/forum/$postId'
    | '/api/public/forum/rules'
    | '/api/public/profiles/$handle'
    | '/api/public/forum/$postId/vote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  ModeratorsRoute: typeof ModeratorsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SocialsRoute: typeof SocialsRoute
  ArticlesArticleIdRoute: typeof ArticlesArticleIdRoute
  ForumPostIdRoute: typeof ForumPostIdRoute
  UHandleRoute: typeof UHandleRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  ForumIndexRoute: typeof ForumIndexRoute
  ApiPublicArticlesRoute: typeof ApiPublicArticlesRoute
  ApiPublicCommentsRoute: typeof ApiPublicCommentsRoute
  ApiPublicForumRoute: typeof ApiPublicForumRouteWithChildren
  ApiPublicAuthLoginRoute: typeof ApiPublicAuthLoginRoute
  ApiPublicAuthMeRoute: typeof ApiPublicAuthMeRoute
  ApiPublicAuthRegisterRoute: typeof ApiPublicAuthRegisterRoute
  ApiPublicAvatarsFileRoute: typeof ApiPublicAvatarsFileRoute
  ApiPublicProfilesHandleRoute: typeof ApiPublicProfilesHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderators': {
      id: '/moderators'
      path: '/moderators'
      fullPath: '/moderators'
      preLoaderRoute: typeof ModeratorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/socials': {
      id: '/socials'
      path: '/socials'
      fullPath: '/socials'
      preLoaderRoute: typeof SocialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$articleId': {
      id: '/articles/$articleId'
      path: '/articles/$articleId'
      fullPath: '/articles/$articleId'
      preLoaderRoute: typeof ArticlesArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/': {
      id: '/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$postId': {
      id: '/forum/$postId'
      path: '/forum/$postId'
      fullPath: '/forum/$postId'
      preLoaderRoute: typeof ForumPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/articles': {
      id: '/api/public/articles'
      path: '/api/public/articles'
      fullPath: '/api/public/articles'
      preLoaderRoute: typeof ApiPublicArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/comments': {
      id: '/api/public/comments'
      path: '/api/public/comments'
      fullPath: '/api/public/comments'
      preLoaderRoute: typeof ApiPublicCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/forum': {
      id: '/api/public/forum'
      path: '/api/public/forum'
      fullPath: '/api/public/forum'
      preLoaderRoute: typeof ApiPublicForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/login': {
      id: '/api/public/auth/login'
      path: '/api/public/auth/login'
      fullPath: '/api/public/auth/login'
      preLoaderRoute: typeof ApiPublicAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/me': {
      id: '/api/public/auth/me'
      path: '/api/public/auth/me'
      fullPath: '/api/public/auth/me'
      preLoaderRoute: typeof ApiPublicAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/register': {
      id: '/api/public/auth/register'
      path: '/api/public/auth/register'
      fullPath: '/api/public/auth/register'
      preLoaderRoute: typeof ApiPublicAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/avatars/$file': {
      id: '/api/public/avatars/$file'
      path: '/api/public/avatars/$file'
      fullPath: '/api/public/avatars/$file'
      preLoaderRoute: typeof ApiPublicAvatarsFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/forum/$postId': {
      id: '/api/public/forum/$postId'
      path: '/$postId'
      fullPath: '/api/public/forum/$postId'
      preLoaderRoute: typeof ApiPublicForumPostIdRouteImport
      parentRoute: typeof ApiPublicForumRoute
    }
    '/api/public/forum/rules': {
      id: '/api/public/forum/rules'
      path: '/rules'
      fullPath: '/api/public/forum/rules'
      preLoaderRoute: typeof ApiPublicForumRulesRouteImport
      parentRoute: typeof ApiPublicForumRoute
    }
    '/api/public/profiles/$handle': {
      id: '/api/public/profiles/$handle'
      path: '/api/public/profiles/$handle'
      fullPath: '/api/public/profiles/$handle'
      preLoaderRoute: typeof ApiPublicProfilesHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/forum/$postId/vote': {
      id: '/api/public/forum/$postId/vote'
      path: '/vote'
      fullPath: '/api/public/forum/$postId/vote'
      preLoaderRoute: typeof ApiPublicForumPostIdVoteRouteImport
      parentRoute: typeof ApiPublicForumPostIdRoute
    }
  }
}

interface ApiPublicForumPostIdRouteChildren {
  ApiPublicForumPostIdVoteRoute: typeof ApiPublicForumPostIdVoteRoute
}

const ApiPublicForumPostIdRouteChildren: ApiPublicForumPostIdRouteChildren = {
  ApiPublicForumPostIdVoteRoute: ApiPublicForumPostIdVoteRoute,
}

const ApiPublicForumPostIdRouteWithChildren =
  ApiPublicForumPostIdRoute._addFileChildren(ApiPublicForumPostIdRouteChildren)

interface ApiPublicForumRouteChildren {
  ApiPublicForumPostIdRoute: typeof ApiPublicForumPostIdRouteWithChildren
  ApiPublicForumRulesRoute: typeof ApiPublicForumRulesRoute
}

const ApiPublicForumRouteChildren: ApiPublicForumRouteChildren = {
  ApiPublicForumPostIdRoute: ApiPublicForumPostIdRouteWithChildren,
  ApiPublicForumRulesRoute: ApiPublicForumRulesRoute,
}

const ApiPublicForumRouteWithChildren = ApiPublicForumRoute._addFileChildren(
  ApiPublicForumRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  ModeratorsRoute: ModeratorsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SocialsRoute: SocialsRoute,
  ArticlesArticleIdRoute: ArticlesArticleIdRoute,
  ForumPostIdRoute: ForumPostIdRoute,
  UHandleRoute: UHandleRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  ForumIndexRoute: ForumIndexRoute,
  ApiPublicArticlesRoute: ApiPublicArticlesRoute,
  ApiPublicCommentsRoute: ApiPublicCommentsRoute,
  ApiPublicForumRoute: ApiPublicForumRouteWithChildren,
  ApiPublicAuthLoginRoute: ApiPublicAuthLoginRoute,
  ApiPublicAuthMeRoute: ApiPublicAuthMeRoute,
  ApiPublicAuthRegisterRoute: ApiPublicAuthRegisterRoute,
  ApiPublicAvatarsFileRoute: ApiPublicAvatarsFileRoute,
  ApiPublicProfilesHandleRoute: ApiPublicProfilesHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
